import styled from "@emotion/styled"
import { Link } from "react-router-dom"
import "../landing.css"

const Container = styled.div`
  width: 100%;
  height: 100%;
  min-height: 100vh;
  max-height: 100vh;
`

const Logo = styled.div`
  width: 100%;
  max-width: 200px;

  img {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }
`

export function HomePage() {
  return (
    <Container>
      <div className="section overflow-hidden">
        <div className="container mt-2xl mb-2xl">
          <div className="row">
            <div className="column align-center" style={{ gap: "20px" }}>
              <Logo>
                <img src="/logo.svg" alt="Composer Pal Logo" />
              </Logo>

              <h1 className="test-giga text-center">
                Unleash your musical genius
                <br />
                with <span className="spanLogo">Composer Pal</span>.
              </h1>
              <p
                className="text-lg text-center max-w-lg"
                style={{ color: "#495057" }}
              >
                {" "}
                With Composer Pal, you can effortlessly create beautiful
                melodies and compositions. Get inspired with unique song samples
                generated by AI and bring your music to life.
              </p>
              <Link to="/search" className="button xl main mt-lg w-button">
                {" "}
                Start creating your masterpiece today.
              </Link>
              <div className="text-sm muted">
                3 free excerpts • No credit card required
              </div>
              {/* <div className="text-sm mt-2xl text-center">
                Show credibility with social proof. Logos of press coverage or
                biggest customers
              </div>
              <div
                className="
                row
                items-center
                mt-lg
                _w-full
                max-w-lg
                wrap
                justify-center
              "
              >
                <div className="logo-container">
                  <img
                    src="http://api.writesonic.com/static/images/Groups.png"
                    alt="intercom logo"
                    className="intercom"
                  />
                </div>
                <div className="logo-container">
                  <img
                    src="http://api.writesonic.com/static/images/Group.png"
                    alt=""
                    className="buffer"
                  />
                </div>
                <div className="logo-container ph">
                  <img
                    src="http://api.writesonic.com/static/images/product-hunt-1.png"
                    alt=""
                    className="product-hunt"
                  />
                </div>
                <div className="logo-container">
                  <img
                    src="http://api.writesonic.com/static/images/icon_slack.png"
                    alt=""
                    className="slack"
                  />
                </div>
                <div className="logo-container">
                  <img
                    src="http://api.writesonic.com/static/images/580b57fcd9996e24bc43c513.png"
                    alt=""
                    className="airbnb"
                  />
                </div>
              </div> */}
            </div>
          </div>
        </div>

        <div className="circle"></div>
      </div>
      {/* <div className="section">
        <img
          src="http://api.writesonic.com/static/images/product-shot.png"
          srcSet="
        http://api.writesonic.com/static/images/product-shot-p-500.png  500w,
        http://api.writesonic.com/static/images/product-shot-p-800.png 800w,
        http://api.writesonic.com/static/images/product-shot-p-1080.png 1080w,
        http://api.writesonic.com/static/images/product-shot.png 1521w
      "
          sizes="(max-width: 479px) 93vw, (max-width: 767px) 94vw, 720px"
          data-w-id="a4177896-a5e5-6c6a-0980-01ce8ea2054a"
          style={{ opacity: 0 }}
          alt=""
          className="product-shot"
        />
      </div> */}
      <div className="section">
        <div className="container mt-2xl mb-2xl">
          <div className="row">
            <div className="column align-center">
              <h2
                className="max-w-lg text-center mb-2xl text-2xl"
                style={{ color: "white" }}
              >
                Unleash your musical genius
                <br /> with Composer Pal.
              </h2>
              <p className="text-lg text-center max-w-md">
                Say goodbye to writer&#39;s block and hello to endless
                inspiration. Composer Pal uses cutting-edge AI technology to
                provide you with a wide range of song samples based on your
                prompts, allowing you to create music that is truly unique and
                captivating. Whether you&#39;re a seasoned composer or just
                starting out, Composer Pal will be your ultimate creative
                companion.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="section">
        <div className="container">
          <div className="row items-center v-t">
            <div className="column align-left p-2xl">
              <h6 className="max-w-lg">#1 Feature</h6>
              <h2 className="max-w-lg" style={{ color: "#4c41cc" }}>
                Unlock your creative potential with AI-generated music.
              </h2>
              <p className="text-lg">
                {" "}
                Don&#39;t let writer&#39;s block hold you back. With Composer
                Pal, you can unleash your creativity by generating music
                excerpts based on AI prompts. Get inspired and explore new
                musical possibilities with just a few clicks.
              </p>
            </div>
            <div className="column align-center p-2xl">
              <img
                src="http://api.writesonic.com/static/images/marginalia-coming-soon.png"
                alt=""
                className="feature-card"
              />
            </div>
          </div>
          <div className="row reverse items-center v-t">
            <div className="column align-left p-2xl">
              <h6 className="max-w-lg">#2 Feature</h6>
              <h2 className="max-w-lg" style={{ color: "#4c41cc" }}>
                Unlock your musical genius with Composer Pal.
              </h2>
              <p className="text-lg">
                {" "}
                Don&#39;t let writer&#39;s block hold you back. With Composer
                Pal, you can tap into a world of endless creative possibilities.
                Manipulate music excerpts on our intuitive and interactive UI to
                create unique compositions that will leave your audience in awe.
                Let your musical genius shine with Composer Pal.
              </p>
            </div>
            <div className="column align-center p-2xl">
              <img
                src="http://api.writesonic.com/static/images/marginalia-online-shopping.png"
                alt=""
                className="feature-card"
              />
            </div>
          </div>
          <div className="row items-center v-t">
            <div className="column align-left p-2xl">
              <h6 className="max-w-lg">#3 Feature</h6>
              <h2 className="max-w-lg" style={{ color: "#4c41cc" }}>
                Unlock your musical potential with genre-specific inspiration.
              </h2>
              <p className="text-lg">
                {" "}
                Don&#39;t let writer&#39;s block hold you back. Composer Pal
                uses generative AI to provide genre-specific song samples,
                giving you the inspiration you need to create your next
                masterpiece. Explore different music genres and let your
                creativity soar.
              </p>
            </div>
            <div className="column align-center p-2xl">
              <img
                src="http://api.writesonic.com/static/images/marginalia-order-complete.png"
                alt=""
                className="feature-card"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="section main mt-2xl">
        <div className="container mt-2xl mb-2xl">
          <div className="row items-center">
            <div className="column align-center">
              <h1 className="max-w-lg text-giga text-center text-white">
                Unleash your creativity and compose like never before with
                Composer Pal.
              </h1>
              <Link
                to="/search"
                className="button xl main white mt-lg w-button"
              >
                {" "}
                Start creating your masterpiece today.
              </Link>
              <div className="faded text-sm mt-lg">
                3 free excerpts • No credit card required
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="section pb-2xl-m">
        <div className="container mt-xl mb-2xl">
          <div className="row mt-xl v-l">
            <div className="column align-left">
              <div className="muted text-sm">Made with ❤️ by AE Studio</div>
            </div>
          </div>
        </div>
      </div>
    </Container>
  )
}
